Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 600
  config.ssh.insert_key = false

  config.vm.box = "alvistack/ubuntu-24.04"

  config.vm.define "marboccuS" do |master|
    master.vm.hostname = "marboccuS"
    master.vm.network "private_network", ip: "192.168.56.110"

    master.vm.provision "shell", path: "scripts/run.sh"

    master.vm.provider "libvirt" do |lv|
      lv.memory = "2048"
      lv.cpus = "2"
      lv.cpu_mode = "host-passthrough"
      lv.graphics_type = "none"
    end
  end
end
