Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-22.04"

  config.vm.define "marboccuS" do |master|
    master.vm.hostname = "marboccuS"
    master.vm.network "private_network", ip: "192.168.56.110"

    master.vm.provision "shell", path: "scripts/run.sh"

    master.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end
  end
end
