Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -y
    echo "192.168.56.110 marboccuW" | sudo tee /etc/hosts
    echo "192.168.56.111 marboccuSW" | sudo tee -a /etc/hosts
  SHELL

  config.vm.box = "ubuntu/jammy64"

  config.vm.define "marboccuW" do |master|
    master.vm.hostname = "marboccuW"
    master.vm.network "private_network", ip: "192.168.56.110"

    master.vm.provision "shell", path: "scripts/k3s_master.sh"

    master.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end
  end

  config.vm.define "marboccuSW" do |agent|
    agent.vm.hostname = "marboccuSW"
    agent.vm.network "private_network", ip: "192.168.56.111"

    agent.vm.provision "shell", path: "scripts/k3s_agent.sh", args: ["192.168.56.110"]

    agent.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end
  end

end
